### ISSUE TITLE
Arch Linux support

### ISSUE THREAD

**Issue by spk83** [andrewrothstein/ansible-python#1]
Ansible has started barfing on Archlinux test. `ansible_distribution` is set to `Arch Linux` in ansible facts and hence ansible is not able to find `vars/Archlinux.yml` while running first task of finding vars file. Should we update the task to look for case-whitespace insensitive filenames? or update the `Archlinux.yml` to `Arch Linux.yml`?

**Comment by spk83** [comment]
encountered during this build - https://travis-ci.org/spk83/ansible-supervisord/jobs/280672545

**Comment by andrewrothstein** [comment]
waiting for https://github.com/ansible/ansible/pull/30723 to get released

**Comment by spk83** [comment]
Closed by https://github.com/andrewrothstein/ansible-python/commit/9bac29062ba691fda75a7cf4f6d7cf2c1a29cd47
