### ISSUE TITLE
Will fail without `sudo` 

### ISSUE THREAD

**Issue by martin-braun** [andrewrothstein/ansible-python#2]
I try to install python on a machine with `root` that has no `sudo` installed, but it fails, because `sudo` cannot be found.

**Comment by andrewrothstein** [comment]
this is another bootstrapping problem. I have a sudo role but it relies on being invoked as root. Most OSes come with sudo already baked in. Most base container images don't, but the main entry point is entered as root. This is another example of something I bake into my base image (docker-ansible) with shell script magic.

**Comment by martin-braun** [comment]
Well I found `coglinev3.ansible_python` which will simply install Python using the current user via `raw` module. I'm new to Ansible, but based on my current understanding: Couldn't you just use the default user and require someone to use `become` when invoking your role from the outside?

I mean, give the choice to the user which user should be used to install Python, as `coglinev3.ansible_python` did it. I deal with Debian and Alpine containers via `root` and your role prevented me from constructing a hybrid configuration, because some Debian machines would miss `sudo` whereas all Alpine machines would miss `python`.

Well, my problem is solved now, I just wanted to share the problems I had with this package.
