### ISSUE TITLE
vars is a directory

### ISSUE THREAD

**Issue by martin-braun** [andrewrothstein/ansible-python#3]
Trying to run this on an Alpine Container and it fails with:

```
(item=/Users/marty/.ansible/roles/andrewrothstein.python/vars/) => {"ansible_facts": {}, "ansible_included_var_files": [], "ansible_loop_var": "item", "changed": false, "item": "/Users/marty/.ansible/roles/andrewrothstein.python/vars/", "message": "an error occurred while trying to read the file '/Users/marty/.ansible/roles/andrewrothstein.python/vars': [Errno 21] Is a directory: b'/Users/marty/.ansible/roles/andrewrothstein.python/vars'. [Errno 21] Is a directory: b'/Users/marty/.ansible/roles/andrewrothstein.python/vars'"}
```

How can it resolve for `ansible_distribution` without `python` being available in the first place?

**Comment by andrewrothstein** [comment]
it can't. this role isn't really meant for bootstrapping Ansible/python. it came from a time/place where the OS, e.g. CentOS 7, came bundled with python2.7 and I wanted to install python3. using Ansible to bootstrap a python installation is beyond the scope of this role. I generally use shell scripts to bootstrap python/Ansible within containers. Take a peek at my docker-ansible repo.

**Comment by andrewrothstein** [comment]
U may consider the ansible-bender project if ur looking for a way to build containers with ansible without necessarily having to bake python and ansible itself into the image itself.

**Comment by martin-braun** [comment]
Thanks for clarification. I picked your package, because of the many downloads, but I eventually found `coglinev3.ansible_python` which is exactly that kind of bootstrapping that I was looking for. Thank you for the quick response! :)
